In [1]:
import pandas as pd
df = pd.read_csv('train.csv')
print(df.shape)
df.head()

(45528, 19)

,customer_id,name,age,gender,owns_car,owns_house,no_of_children,net_yearly_income,no_of_days_employed,occupation_type,total_family_members,migrant_worker,yearly_debt_payments,credit_limit,credit_limit_used(%),credit_score,prev_defaults,default_in_last_6months,credit_card_default
0,CST_115179,ita Bose,46,F,N,Y,0.0,107934.04,612.0,Unknown,1.0,1.0,33070.28,18690.93,73,544.0,2,1,1
1,CST_121920,Alper Jonathan,29,M,N,Y,0.0,109862.62,2771.0,Laborers,2.0,0.0,15329.53,37745.19,52,857.0,0,0,0
2,CST_109330,Umesh Desai,37,M,N,Y,0.0,230153.17,204.0,Laborers,2.0,0.0,48416.60,41598.36,43,650.0,0,0,0
3,CST_128288,Rie,39,F,N,Y,0.0,122325.82,11941.0,Core staff,2.0,0.0,22574.36,32627.76,20,754.0,0,0,0
4,CST_151355,McCool,46,M,Y,Y,0.0,387286.00,1459.0,Core staff,1.0,0.0,38282.95,52950.64,75,927.0,0,0,0

In [14]:
df["credit_card_default"].value_counts(normalize=True)

credit_card_default
0    0.911171
1    0.088829
Name: proportion, dtype: float64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30193 entries, 1 to 45526
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      30193 non-null  int64
 1   gender                   30193 non-null  object
 2   owns_car                 29833 non-null  object
 3   owns_house               30193 non-null  object
 4   no_of_children           30193 non-null  float64
 5   net_yearly_income        30193 non-null  float64
 6   no_of_days_employed      30193 non-null  float64
 7   occupation_type          30193 non-null  object
 8   total_family_members     30193 non-null  float64
 9   migrant_worker           30193 non-null  float64
 10  yearly_debt_payments     30193 non-null  float64
 11  credit_limit             30193 non-null  float64
 12  credit_limit_used(%)     30193 non-null  int64
 13  credit_score             30193 non-null  float64
 14  prev_defaults            30193 non-null  int64
 15  default_in_last_6months  30193 non-null  int64
 16  credit_card_default      30193 non-null  int64
dtypes: float64(8), int64(5), object(4)
memory usage: 4.1+ MB

In [4]:
cat_feats = [col for col in df.columns if df[col].dtypes == "object"]
num_feats =  [col for col in df.columns if df[col].dtypes != "object"]

print("no of cat feats: ", len(cat_feats))
print("no of num feats: ", len(num_feats))

no of cat feats:  6
no of num feats:  13

In [16]:
cat_feats

['customer_id', 'name', 'gender', 'owns_car', 'owns_house', 'occupation_type']

In [17]:
num_feats

['age',
 'no_of_children',
 'net_yearly_income',
 'no_of_days_employed',
 'total_family_members',
 'migrant_worker',
 'yearly_debt_payments',
 'credit_limit',
 'credit_limit_used(%)',
 'credit_score',
 'prev_defaults',
 'default_in_last_6months',
 'credit_card_default']

In [18]:
df = df.drop(['customer_id', 'name'], axis=1)
df

KeyError: "['customer_id', 'name'] not found in axis"

In [19]:
for col in df.columns:
    temp = df[col].isnull().sum()
    print(f'Column {col} contains {temp} null values.')

Column age contains 0 null values.
Column gender contains 0 null values.
Column owns_car contains 360 null values.
Column owns_house contains 0 null values.
Column no_of_children contains 0 null values.
Column net_yearly_income contains 0 null values.
Column no_of_days_employed contains 0 null values.
Column occupation_type contains 0 null values.
Column total_family_members contains 0 null values.
Column migrant_worker contains 0 null values.
Column yearly_debt_payments contains 0 null values.
Column credit_limit contains 0 null values.
Column credit_limit_used(%) contains 0 null values.
Column credit_score contains 0 null values.
Column prev_defaults contains 0 null values.
Column default_in_last_6months contains 0 null values.
Column credit_card_default contains 0 null values.

In [20]:
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    print(f"\nColumn: {col}")
    print(df[col].value_counts())

Column: gender
gender
F      18490
M      11702
XNA        1
Name: count, dtype: int64

Column: owns_car
owns_car
N    18553
Y    11280
Name: count, dtype: int64

Column: owns_house
owns_house
Y    20623
N     9570
Name: count, dtype: int64

Column: occupation_type
occupation_type
Laborers                 7834
Sales staff              4549
Core staff               3939
Managers                 3071
Drivers                  2665
High skill tech staff    1621
Accountants              1432
Medicine staff           1236
Security staff           1003
Cooking staff             867
Cleaning staff            640
Private service staff     380
Low-skill Laborers        329
Waiters/barmen staff      198
Secretaries               193
Realty agents              95
HR staff                   77
IT staff                   64
Name: count, dtype: int64

In [21]:
df.dropna(subset=num_feats, inplace=True)
print(df.shape)

df[num_feats].isnull().sum()

(30193, 17)

age                        0
no_of_children             0
net_yearly_income          0
no_of_days_employed        0
total_family_members       0
migrant_worker             0
yearly_debt_payments       0
credit_limit               0
credit_limit_used(%)       0
credit_score               0
prev_defaults              0
default_in_last_6months    0
credit_card_default        0
dtype: int64

In [22]:
df = df[df['occupation_type'] != 'Unknown']
print(df.shape)

(30193, 17)

In [23]:
df = df[df['gender'] != 'XNA']
print(df.shape)

(30192, 17)

In [24]:
laborers_to_drop = df[df['occupation_type'] == 'Laborers'].sample(n=192, random_state=42).index
df = df.drop(laborers_to_drop)
print(df.shape)

(30000, 17)